services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    working_dir: '/app'
    user: node
    ports:
      - 4000:3000
    environment:
      - SENTRY_DSN="${SENTRY_DSN}"
      - APP_NAME="${APP_NAME}"
      - APP_URL="${APP_URL}""
      - APP_ENVIRONMENT="${APP_ENVIRONMENT}"
      - COMPATIBILITY_DATE="${COMPATIBILITY_DATE}"
      - NUXT_RESEND_API_KEY="${NUXT_RESEND_API_KEY}"
      - SENTRY_DSN="${SENTRY_DSN}"
      - SENTRY_AUTH_TOKEN="${SENTRY_AUTH_TOKEN}"
      - SERVICE_FQDN_FRONTEND_4000
    labels:
      - traefik.enable=true
      - "traefik.http.routers.<unique_router_name>.rule=Host(`chartman2fr.torm.lan`) && PathPrefix(`/`)"
      - traefik.http.routers.<unique_router_name>.entryPoints=http
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro