version: "3.8"

services:
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    command:  sh -c "pnpm run dev"
    working_dir: '/app'
    user: node
    tty: true
    volumes:
      - './:/app'
    environment:
      - PUID="${UID}"
      - PGID="${GID}"
      - UMASK="${USMAK}"
    labels:
      # Ajout dans traefik
      - "traefik.enable=true"
      
      # HTTP
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=http"

      # HTTPS
      - "traefik.http.routers.${APP_NAME}-secure.service=chartman2-fr-secure"
      - "traefik.http.routers.${APP_NAME}-secure.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_NAME}-secure.tls=true"

      # WSS
      - "traefik.http.routers.${APP_NAME}-wss.service=chartman2-fr-wss"
      - "traefik.http.routers.${APP_NAME}-wss.rule=Host(`${APP_WS_URL}`)"
      - "traefik.http.routers.${APP_NAME}-wss.entrypoints=https"
      - "traefik.http.routers.${APP_NAME}-wss.tls=true"
      
      # Redirection
      - "traefik.http.middlewares.${APP_NAME}-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${APP_NAME}-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.${APP_NAME}.middlewares=chartman2-fr-redirect"

      # Port interne
      - "traefik.http.services.${APP_NAME}-secure.loadbalancer.server.port=3000"
      - "traefik.http.services.${APP_NAME}-wss.loadbalancer.server.port=24678"
    expose:
      - 3000
      - 24678
    networks:
      - chartman2-fr-network

networks:
  chartman2-fr-network:
    name: projects_local_dev
    external: true