version: '3'

tasks:
  build:
    desc: Construction des services Docker
    cmds:
      - UID_GID="$(id -u):$(id -g)" docker compose build
  up:
    desc: Démarrage des services Docker
    cmds:
      - UID_GID="$(id -u):$(id -g)" docker compose up -d
      - cat ~/.config/code-server/config.yaml
      - docker compose exec frontend sh
  down:
    desc: Arrêt des services Docker
    cmds:
      - docker compose down
  logs:
    desc: Logs des services
    cmds:
      - docker compose logs -f
  f-restart:
    desc: Redémarrage du service frontend
    cmds:
      - docker compose restart frontend