services:
  frontend:
    build:
      context: ./../
      dockerfile: ./.production/Dockerfile
    working_dir: '/app'
    user: node
    ports:
      - 4000:3000
    environment:
      - SENTRY_DSN: ${SENTRY_DSN}
      - APP_NAME: ${APP_NAME}
      - APP_URL: ${APP_URL}
      - APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      - COMPATIBILITY_DATE: ${COMPATIBILITY_DATE}
      - NUXT_RESEND_API_KEY: ${NUXT_RESEND_API_KEY}
      - SENTRY_DSN: ${SENTRY_DSN}